#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80


FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY *.sln .
COPY ["src/Spg.AutoTeileShop.API/Spg.AutoTeileShop.API.csproj", "/Spg.AutoTeileShop.API/"]
COPY ["src/Spg.AutoTeileShop.Application/Spg.AutoTeileShop.Application.csproj", "/Spg.AutoTeileShop.Application/"]
COPY ["src/Spg.AutoTeileShop.Domain/Spg.AutoTeileShop.Domain.csproj", "/Spg.AutoTeileShop.Domain/"]
COPY ["src/Spg.AutoTeileShop.Infrastructure/Spg.AutoTeileShop.Infrastructure.csproj", "/Spg.AutoTeileShop.Infrastructure/"]
COPY ["src/Spg.AutoTeileShop.Repository2/Spg.AutoTeileShop.Repository2.csproj", "/Spg.AutoTeileShop.Repository2/"]
COPY ["src/Spg.AutoTeileShop.DbExtentions/Spg.AutoTeileShop.DbExtentions.csproj", "/Spg.AutoTeileShop.DbExtentions/"]
COPY ["src/Spg.AutoTeileShop.ServiceExtentions/Spg.AutoTeileShop.ServiceExtentions.csproj", "/Spg.AutoTeileShop.ServiceExtentions/"]
COPY ["src/Spg.AutoTeileShop.API/db/AutoTeileShop.db", "/Spg.AutoTeileShop.API/db/"]
RUN dotnet restore "/Spg.AutoTeileShop.API/Spg.AutoTeileShop.API.csproj"
COPY . .
WORKDIR "src/Spg.AutoTeileShop.API"
RUN dotnet build "Spg.AutoTeileShop.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Spg.AutoTeileShop.API.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM alpine:3.12 AS db
RUN apk update && apk upgrade
RUN apk add --no-cache sqlite~=3.32.1-r0

#FROM openjdk:8u131-jdk-alpine
#VOLUME AutoTeileDB

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Spg.AutoTeileShop.API.dll"]